version: "3.8"
services:
  Afisha_api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - database
  database:
    image: 'postgres:14'
    hostname: 'Afisha_api'
    env_file:
      - '.env'
    environment:
      POSTGRES_DB:  = '${DB_NAME}'
      POSTGRES_USER:  = '${DB_USER}'
      POSTGRES_PASSWORD:  = '${DB_PASS}'
    ports:
      - '5433:5433'
    volumes:
      - 'Afisha_data:/var/lib/postgresql/data
volumes:
  Afisha_data: