# Generated by Django 5.1 on 2024-08-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_category_searchtag_review_director_review_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_reviews', to='MovieApp.director'),
        ),
    ]
